CREATE TABLE clientes_db (
id BIGINT GENERATED ALWAYS AS INDENTIFY PRIMARY KEY,
nome VARCHAR(255) NOT NULL,
email VARCHAR(255) UNIQUE,
telefone VARCHAR(20) NOT NULL
created_at TIMESTAMP NOT NULL DEFAULT NOW(),
updated_at TIMESTAMP NOT NULL DEFAULT NOW()

);
